### PR TITLE
F update imagekit into master

### PR DESCRIPTION
**Pull request by andrewbohm**

### CODE REVIEW

**Comment by andrewbohm** [comment]
Merge into master

**Comment by dsasko** [comment]
@andrewbohm your changes seem to work fine on Strapi v3.0.1.
Thank you for the time and effort!

**Comment by andrewbohm** [comment]
@dsasko you're welcome. I'll keep monitoring the project and if any other issues arrise feel free to contact me and I can help out if needed.

**Comment by andrewbohm** [comment]
@dsasko, Can you please update the npm package when you have a chance?

**Pull request merged**
